// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB15fi6E3qQ3ca-UzMgx7GArt2q8ToYZX4',
    appId: '1:553258655217:web:f6accd0112dbdb787db850',
    messagingSenderId: '553258655217',
    projectId: 'e-konsul-2023',
    authDomain: 'e-konsul-2023.firebaseapp.com',
    storageBucket: 'e-konsul-2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJtaH1zmQPr1NwV9mDHyE5292sLf6S1X8',
    appId: '1:553258655217:android:168425f094bfce2c7db850',
    messagingSenderId: '553258655217',
    projectId: 'e-konsul-2023',
    storageBucket: 'e-konsul-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6TQwjwg_FjXvcusPHPAqUSqJKbBxb_Qo',
    appId: '1:553258655217:ios:8cefb145b341f1007db850',
    messagingSenderId: '553258655217',
    projectId: 'e-konsul-2023',
    storageBucket: 'e-konsul-2023.appspot.com',
    iosClientId: '553258655217-1dradhdoqckmbd98jtc7e7pii4mqc8e6.apps.googleusercontent.com',
    iosBundleId: 'com.example.eKonsul',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6TQwjwg_FjXvcusPHPAqUSqJKbBxb_Qo',
    appId: '1:553258655217:ios:8cefb145b341f1007db850',
    messagingSenderId: '553258655217',
    projectId: 'e-konsul-2023',
    storageBucket: 'e-konsul-2023.appspot.com',
    iosClientId: '553258655217-1dradhdoqckmbd98jtc7e7pii4mqc8e6.apps.googleusercontent.com',
    iosBundleId: 'com.example.eKonsul',
  );
}
